### PR TITLE
Add 4.2 testing

### PR DESCRIPTION
**Pull request by greg-mckeon**

### CODE REVIEW

**Comment by MaBeuLux88** [comment]
I don't see the tests results for the 4.2 run. Are you planning to add them later on?
@shawnbmccarthy Maybe you want to have a look too? I didn't give this a spin but LGTM.

**Comment by greg-mckeon** [comment]
I haven't updated the README yet - I would like to do so both here and on the master branch.  I'll push that later today.

**Comment by MaBeuLux88** [comment]
Okay perfect then. One PR for each?

**Comment by greg-mckeon** [comment]
Yep.  Added the 4.2 README.

**Comment by greg-mckeon** [comment]
@MaBeuLux88 could you merge this?

**Pull request merged**
