### PR TITLE
Add 4.2 testing.

### PR DESCRIPTION
**Pull request by greg-mckeon**

### CODE REVIEW

**Comment by MaBeuLux88** [comment]
The point of this repo is to compare AWS DocumentDB service and MongoDB.
DocumentDB only supports MongoDB 3.6 so if we want to compare what is actually comparable, we need to keep this 3.6 level for both systems.
For example, we already know they don't support transactions, that's obvious. We don't need to add a test to validate this.
ping @shawnbmccarthy. What do you think?

**Comment by greg-mckeon** [comment]
I agree, and think that we should keep the 3.6 testing alongside the 4.2 testing.  The 4.2 testing is important since DocumentDB continues to add support for features. Freezing our compatibility testing to a specific MongoDB version creates the impression that DocumentDB is now more compatible with MongoDB than they were a year ago, despite the fact that they support none of the new features from 4.2 or 4.0 and are actually just improving 3.6 compatibility.

**Comment by MaBeuLux88** [comment]
I totally agree with that.
Then I think this PR should go into a "4.2" branch and not into master.

**Comment by greg-mckeon** [comment]
That works for me - are you ok with creating that branch and merging this then?

**Comment by MaBeuLux88** [comment]
Hey,

I created a branch v4.2.
Can you please send a PR to this branch?
It's the same history than master.

Thanks,
Maxime.

PS : I also had an existing branch v4.0.5. Not sure what I should do with
this one now.

**Pull request closed without merging**
